In [4]:
# load the dataset
import pandas as pd
covid = pd.read_csv("EPL20-21.csv")
non_covid = pd.read_csv("EPL24-25.csv")

In [5]:
# filter team names and fulltime goals of each team
covid = covid[['HomeTeam','AwayTeam','FTHG','FTAG']]
non_covid = non_covid[['HomeTeam','AwayTeam','FTHG','FTAG']]

In [6]:
covid.head(), non_covid.head()

(     HomeTeam        AwayTeam  FTHG  FTAG
 0   Brentford         Arsenal     2     0
 1  Man United           Leeds     5     1
 2     Burnley        Brighton     1     2
 3     Chelsea  Crystal Palace     3     0
 4     Everton     Southampton     3     1,
      HomeTeam     AwayTeam  FTHG  FTAG
 0  Man United       Fulham     1     0
 1     Ipswich    Liverpool     0     2
 2     Arsenal       Wolves     2     0
 3     Everton     Brighton     0     3
 4   Newcastle  Southampton     1     0)

In [7]:
# calculate the home-away difference of each season
covid_sample = covid.sample(n=35, random_state=10).copy()
non_covid_sample = non_covid.sample(n=35, random_state=10).copy()
covid_sample["net_different"] = covid_sample["FTHG"] - covid_sample["FTAG"]
non_covid_sample["net_different"] = non_covid_sample["FTHG"] - non_covid_sample["FTAG"]

In [10]:
covid_sample

           HomeTeam        AwayTeam  FTHG  FTAG  net_different
266       Tottenham         Everton     5     0              5
152         Chelsea           Leeds     3     2              1
222       Liverpool       Leicester     2     0              2
241        Man City       Tottenham     2     3             -1
186       Brentford     Aston Villa     2     1              1
65         Brighton         Arsenal     0     0              0
192        West Ham         Norwich     2     0              2
24          Norwich       Leicester     1     2             -1
202       Leicester       Tottenham     2     3             -1
236     Aston Villa         Watford     0     1             -1
280  Crystal Palace        Man City     0     0              0
66   Crystal Palace       Leicester     2     2              0
6           Watford     Aston Villa     3     2              1
362        West Ham        Man City     2     2              0
370         Arsenal         Everton     5     1              4
252      Man United         Watford     0     0              0
56        Brentford       Liverpool     3     3              0
172        West Ham     Southampton     2     3             -1
121  Crystal Palace     Aston Villa     1     2             -1
205         Everton     Aston Villa     0     1             -1
124        Brighton           Leeds     0     0              0
260       Newcastle        Brighton     2     1              1
223          Wolves         Arsenal     0     1             -1
175       Newcastle      Man United     1     1              0
247         Arsenal          Wolves     2     1              1
119       Tottenham           Leeds     2     1              1
43        Liverpool  Crystal Palace     3     0              3
47         Brighton       Leicester     2     1              1
259         Burnley         Chelsea     0     4             -4
78        Newcastle       Tottenham     2     3             -1
1        Man United           Leeds     5     1              4
240     Southampton         Everton     2     0              2
187         Everton        Brighton     2     3             -1
341      Man United       Brentford     3     0              3
238  Crystal Palace         Chelsea     0     1             -1

In [11]:
non_covid_sample

           HomeTeam        AwayTeam  FTHG  FTAG  net_different
266      Man United         Ipswich     3     2              1
152          Wolves         Ipswich     1     2             -1
222     Southampton       Newcastle     1     3             -2
241       Leicester         Arsenal     0     2             -2
186         Ipswich         Chelsea     2     0              2
65         West Ham         Ipswich     4     1              3
192  Crystal Palace         Chelsea     1     1              0
24        Leicester     Aston Villa     1     2             -1
202   Nott'm Forest       Liverpool     1     1              0
236      Man United  Crystal Palace     0     2             -2
280        West Ham       Newcastle     0     1             -1
66          Everton       Newcastle     0     0              0
6          West Ham     Aston Villa     1     2             -1
362         Everton     Southampton     2     0              2
370     Bournemouth       Leicester     2     0              2
252         Everton      Man United     2     2              0
56           Wolves       Liverpool     1     2             -1
172       Newcastle     Aston Villa     3     0              3
121       Brentford       Leicester     4     1              3
205       Newcastle          Wolves     3     0              3
124          Wolves     Bournemouth     2     4             -2
260        Man City       Liverpool     0     2             -2
223          Wolves         Arsenal     0     1             -1
175          Wolves      Man United     2     0              2
247  Crystal Palace         Everton     1     2             -1
119       Newcastle        West Ham     0     2             -2
43        Leicester         Everton     1     1              0
47   Crystal Palace      Man United     0     0              0
259       Newcastle   Nott'm Forest     4     3              1
78        Liverpool         Chelsea     2     1              1
1           Ipswich       Liverpool     0     2             -2
240        Brighton         Chelsea     3     0              3
187      Man United       Newcastle     0     2             -2
341     Aston Villa          Fulham     1     0              1
238         Chelsea        West Ham     2     1              1

In [8]:
# ttest via scipy.stats library
from scipy.stats import ttest_ind

# two-sample t-test
t_stat, p_value = ttest_ind(
    non_covid_sample["net_different"],
    covid_sample["net_different"],
    equal_var=False,
    alternative="two-sided"
)

print("Covid mean:", covid_sample["net_different"].mean())
print("Non-covid mean:", non_covid_sample["net_different"].mean())
print("Covid std:", covid_sample["net_different"].std())
print("Non-covid std:", non_covid_sample["net_different"].std())
print("t statistic:", t_stat)
print("p-value:", p_value)

Covid mean: 0.4857142857142857
Non-covid mean: 0.14285714285714285
Covid std: 1.8209795129420383
Non-covid std: 1.751350019486768
t statistic: -0.8028385659852019
p-value: 0.42486950591834094

In [9]:
# interpretation
# Assuming the null hypothesis is true, and there is no difference in home-away mean differences between the two seasons,
# there is a probability of 0.4249 that we would get a sample difference in means where 
# mean home-away difference in non-covid season is greater OR less the mean home-away difference in covid season,
# purely by chance